before_script:
  - npm install
#  - npm start
# Runs local server, does not end

stages:
  - test
  # - deploy

job_runtests:
  stage: test
  script:
    - npm run test
# NEEDS SUDO in shell.. try other env
# job_deploy:
#   stage: deploy
#   script:
#     - gem install dpl
#     - dpl --provider=heroku --app=course-companion --api-key=$HEROKU_PRODUCTION_API_KEY

#   only:
#     - master